const fs = require('fs');
const path = require('path');

const dbPath = path.join(__dirname, '..', 'server_data.json');
const raw = fs.readFileSync(dbPath, 'utf8');
const data = JSON.parse(raw);

const now = Date.now();

// 1. Update Auctions to have urgent and realistic live countdowns for 08/09/2026 & 09/09/2026
const updatedAuctions = [
    {
        id: 1,
        flightCode: 'FL-VU130-260908',
        flightNumber: 'VU130',
        route: 'SGN - HAN',
        origin: 'SGN',
        destination: 'HAN',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Hà Nội',
        etd: '20:45 · 08/09/2026',
        eta: '23:00 · 08/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 3500,
        startingPriceKg: 18000,
        currentPriceKg: 56500,
        minStep: 500,
        endTime: new Date(now + 48 * 60 * 1000).toISOString(), // ~48 mins remaining
        status: 'OPEN',
        leadingAgentCode: 'AG-0892',
        leadingAgentName: 'Công ty TNHH Vận tải ABC Logistics',
        bidsCount: 10,
        specialNotes: 'Hàng tổng hợp, hỗ trợ kho lạnh bảo quản thực phẩm & dược phẩm.',
        cutOffTime: '17:45 · 08/09/2026',
        isAnonymous: true,
        etdIso: new Date(now + 3 * 3600 * 1000 + 48 * 60 * 1000).toISOString()
    },
    {
        id: 2,
        flightCode: 'FL-VU224-260908',
        flightNumber: 'VU224',
        route: 'SGN - DAD',
        origin: 'SGN',
        destination: 'DAD',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Đà Nẵng',
        etd: '21:30 · 08/09/2026',
        eta: '22:50 · 08/09/2026',
        aircraft: 'Airbus A320-200',
        capacityKg: 2000,
        startingPriceKg: 12000,
        currentPriceKg: 14500,
        minStep: 500,
        endTime: new Date(now + 95 * 60 * 1000).toISOString(), // ~1h 35m remaining
        status: 'OPEN',
        leadingAgentCode: 'AG-1024',
        leadingAgentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        bidsCount: 4,
        specialNotes: 'Ưu tiên bưu kiện bưu phẩm thương mại điện tử chuyển phát nhanh.',
        cutOffTime: '18:30 · 08/09/2026',
        isAnonymous: true,
        etdIso: new Date(now + 4 * 3600 * 1000 + 35 * 60 * 1000).toISOString()
    },
    {
        id: 3,
        flightCode: 'FL-VU340-260908',
        flightNumber: 'VU340',
        route: 'HAN - PQC',
        origin: 'HAN',
        destination: 'PQC',
        originName: 'Hà Nội',
        destName: 'Phú Quốc',
        etd: '22:45 · 08/09/2026',
        eta: '01:00 · 09/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 4000,
        startingPriceKg: 22000,
        currentPriceKg: 30000,
        minStep: 1000,
        endTime: new Date(now + 170 * 60 * 1000).toISOString(), // ~2h 50m remaining
        status: 'OPEN',
        leadingAgentCode: 'AG-1024',
        leadingAgentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        bidsCount: 6,
        specialNotes: 'Hàng hải sản đông lạnh tươi sống đóng thùng xốp tiêu chuẩn IATA.',
        cutOffTime: '19:45 · 08/09/2026',
        isAnonymous: true,
        etdIso: new Date(now + 5 * 3600 * 1000 + 50 * 60 * 1000).toISOString()
    },
    {
        id: 4,
        flightCode: 'FL-VU132-260908',
        flightNumber: 'VU132',
        route: 'SGN - HAN',
        origin: 'SGN',
        destination: 'HAN',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Hà Nội',
        etd: '10:00 · 08/09/2026',
        eta: '12:15 · 08/09/2026',
        aircraft: 'Airbus A321-200',
        capacityKg: 3000,
        startingPriceKg: 18000,
        currentPriceKg: 22000,
        minStep: 500,
        endTime: new Date(now - 7 * 3600 * 1000).toISOString(),
        status: 'CLOSED',
        leadingAgentCode: 'AG-0892',
        leadingAgentName: 'ABC Logistics',
        bidsCount: 12,
        winnerAgentCode: 'AG-0892',
        winnerAgentName: 'ABC Logistics',
        winningPriceKg: 22000,
        specialNotes: 'Phiên đã đóng hôm nay, thắng thầu chính thức.',
        cutOffTime: '07:00 · 08/09/2026',
        isAnonymous: true
    },
    {
        id: 5,
        flightCode: 'FL-VU3245-260908',
        flightNumber: 'VU3245',
        route: 'SGN - HAN',
        origin: 'SGN',
        destination: 'HAN',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Hà Nội',
        etd: '14:00 · 08/09/2026',
        eta: '16:15 · 08/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 3000,
        startingPriceKg: 18000,
        currentPriceKg: 57000,
        minStep: 500,
        endTime: new Date(now - 3 * 3600 * 1000).toISOString(),
        status: 'CLOSED',
        leadingAgentCode: 'AG-0892',
        leadingAgentName: 'Công ty TNHH Vận tải ABC Logistics',
        bidsCount: 4,
        specialNotes: 'Tải trọng tổng hợp tiêu chuẩn IATA.',
        cutOffTime: '11:00 · 08/09/2026',
        isAnonymous: true,
        winnerAgentCode: 'AG-0892',
        winnerAgentName: 'Công ty TNHH Vận tải ABC Logistics',
        winningPriceKg: 57000
    },
    {
        id: 6,
        flightCode: 'FL-VU32453-260908',
        flightNumber: 'VU32453',
        route: 'SGN - HAN',
        origin: 'SGN',
        destination: 'HAN',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Hà Nội',
        etd: '16:00 · 08/09/2026',
        eta: '18:15 · 08/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 3000,
        startingPriceKg: 18000,
        currentPriceKg: 25000,
        minStep: 500,
        endTime: new Date(now - 1 * 3600 * 1000).toISOString(),
        status: 'CLOSED',
        leadingAgentCode: 'AG-0892',
        leadingAgentName: 'Công ty TNHH Vận tải ABC Logistics',
        bidsCount: 2,
        specialNotes: 'Tải trọng tổng hợp tiêu chuẩn IATA.',
        cutOffTime: '13:00 · 08/09/2026',
        isAnonymous: true,
        winnerAgentCode: 'AG-0892',
        winnerAgentName: 'Công ty TNHH Vận tải ABC Logistics',
        winningPriceKg: 25000
    },
    {
        id: 7,
        flightCode: 'FL-VU450-260909',
        flightNumber: 'VU450',
        route: 'SGN - PQC',
        origin: 'SGN',
        destination: 'PQC',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Phú Quốc',
        etd: '12:10 · 09/09/2026',
        eta: '13:10 · 09/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 3000,
        startingPriceKg: 18000,
        currentPriceKg: 18000,
        minStep: 500,
        endTime: new Date(now + 16 * 3600 * 1000).toISOString(),
        status: 'OPEN',
        leadingAgentCode: 'AG-1024',
        leadingAgentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        bidsCount: 1,
        specialNotes: 'Tải trọng tổng hợp tiêu chuẩn IATA.',
        cutOffTime: '09:10 · 09/09/2026',
        isAnonymous: true
    },
    {
        id: 8,
        flightCode: 'FL-VU510-260909',
        flightNumber: 'VU510',
        route: 'DAD - PQC',
        origin: 'DAD',
        destination: 'PQC',
        originName: 'Đà Nẵng',
        destName: 'Phú Quốc',
        etd: '08:30 · 09/09/2026',
        eta: '10:30 · 09/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 3000,
        startingPriceKg: 18000,
        currentPriceKg: 27000,
        minStep: 500,
        endTime: new Date(now + 12 * 3600 * 1000 + 30 * 60 * 1000).toISOString(),
        status: 'OPEN',
        leadingAgentCode: 'AG-1024',
        leadingAgentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        bidsCount: 2,
        specialNotes: 'Tải trọng tổng hợp tiêu chuẩn IATA.',
        cutOffTime: '05:30 · 09/09/2026',
        isAnonymous: true
    },
    {
        id: 9,
        flightCode: 'FL-VU134-260909',
        flightNumber: 'VU134',
        route: 'SGN - HAN',
        origin: 'SGN',
        destination: 'HAN',
        originName: 'TP. Hồ Chí Minh',
        destName: 'Hà Nội',
        etd: '11:00 · 09/09/2026',
        eta: '13:15 · 09/09/2026',
        aircraft: 'Airbus A321neo Cargo',
        capacityKg: 10000,
        startingPriceKg: 10000,
        currentPriceKg: 10000,
        minStep: 500,
        endTime: new Date(now + 15 * 3600 * 1000).toISOString(),
        status: 'OPEN',
        leadingAgentCode: 'AG-1024',
        leadingAgentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        bidsCount: 1,
        specialNotes: 'Tải trọng tổng hợp tiêu chuẩn IATA. Có hỗ trợ xe nâng pallet.',
        cutOffTime: '08:00 · 09/09/2026',
        isAnonymous: true
    }
];

// 2. Generate clean bids for all auctions
const cleanBids = [
    // Auction 1 (VU130) - 10 bids in last 45 minutes
    {
        id: now - 3 * 60 * 1000,
        timestamp: now - 3 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 56500,
        time: '3 phút trước',
        status: 'HIGHEST',
        weightKg: 3500
    },
    {
        id: now - 6 * 60 * 1000,
        timestamp: now - 6 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 56000,
        time: '6 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 12 * 60 * 1000,
        timestamp: now - 12 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0556',
        agentName: 'Công ty TNHH Tiếp vận Toàn Cầu Golden Star',
        isAnonymous: true,
        priceKg: 41500,
        time: '12 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 18 * 60 * 1000,
        timestamp: now - 18 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 39000,
        time: '18 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 24 * 60 * 1000,
        timestamp: now - 24 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0556',
        agentName: 'Công ty TNHH Tiếp vận Toàn Cầu Golden Star',
        isAnonymous: true,
        priceKg: 25000,
        time: '24 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 30 * 60 * 1000,
        timestamp: now - 30 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 24500,
        time: '30 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 35 * 60 * 1000,
        timestamp: now - 35 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0556',
        agentName: 'Công ty TNHH Tiếp vận Toàn Cầu Golden Star',
        isAnonymous: true,
        priceKg: 23000,
        time: '35 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 40 * 60 * 1000,
        timestamp: now - 40 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 21500,
        time: '40 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 45 * 60 * 1000,
        timestamp: now - 45 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-0556',
        agentName: 'Công ty TNHH Tiếp vận Toàn Cầu Golden Star',
        isAnonymous: true,
        priceKg: 20000,
        time: '45 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },
    {
        id: now - 50 * 60 * 1000,
        timestamp: now - 50 * 60 * 1000,
        auctionId: 1,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 19000,
        time: '50 phút trước',
        status: 'OUTBID',
        weightKg: 3500
    },

    // Auction 2 (VU224)
    {
        id: now - 15 * 60 * 1000,
        timestamp: now - 15 * 60 * 1000,
        auctionId: 2,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 14500,
        time: '15 phút trước',
        status: 'HIGHEST',
        weightKg: 2000
    },
    {
        id: now - 35 * 60 * 1000,
        timestamp: now - 35 * 60 * 1000,
        auctionId: 2,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 13500,
        time: '35 phút trước',
        status: 'OUTBID',
        weightKg: 2000
    },

    // Auction 3 (VU340)
    {
        id: now - 10 * 60 * 1000,
        timestamp: now - 10 * 60 * 1000,
        auctionId: 3,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 30000,
        time: '10 phút trước',
        status: 'HIGHEST',
        weightKg: 4000
    },
    {
        id: now - 25 * 60 * 1000,
        timestamp: now - 25 * 60 * 1000,
        auctionId: 3,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 28000,
        time: '25 phút trước',
        status: 'OUTBID',
        weightKg: 4000
    },

    // Auction 8
    {
        id: now - 20 * 60 * 1000,
        timestamp: now - 20 * 60 * 1000,
        auctionId: 8,
        agentCode: 'AG-1024',
        agentName: 'Công ty CP Giao nhận Kho vận Vinatrans',
        isAnonymous: true,
        priceKg: 27000,
        time: '20 phút trước',
        status: 'HIGHEST',
        weightKg: 3000
    },
    {
        id: now - 45 * 60 * 1000,
        timestamp: now - 45 * 60 * 1000,
        auctionId: 8,
        agentCode: 'AG-0892',
        agentName: 'Công ty TNHH Vận tải ABC Logistics',
        isAnonymous: true,
        priceKg: 26000,
        time: '45 phút trước',
        status: 'OUTBID',
        weightKg: 3000
    }
];

data.auctions = updatedAuctions;
data.bids = cleanBids;
data.version = now;

fs.writeFileSync(dbPath, JSON.stringify(data, null, 2), 'utf8');
console.log('Successfully refreshed server_data.json with realistic live countdowns & clean recent bid timestamps!');
